COPY db/migration/ /usr/src/db/migration/

RUN curl -s https://bintray.com/artifact/download/business/maven/flyway-commandline-3.2.1-linux-x64.tar.gz > /tmp/flyway-3.2.1.tar.gz && \
		tar xzvf /tmp/flyway-3.2.1.tar.gz -C /tmp

#		mv /tmp/apache-maven-3.3.9 /opt && \
#		rm -r /tmp/apache-maven-3.3.9-bin.tar.gz